### ISSUE TITLE
Revive and update for modern Python

### ISSUE THREAD

**Issue by cooljeanius** [SourceryTools/qmtest#1]
qmtest is very old by this point, and yet GCC still contains Makefile targets for it. Try doing `make qmtest-g++` or `make qmtest-gui` in GCC's gcc subdirectory and note that it fails with errors from qmtest nowadays:

```
$ make qmtest-g++ QMTEST_PATH=/opt/qmtest/bin/qmtest
/opt/qmtest/bin/qmtest  -D qmtestsuite create-tdb \
	    -c gcc_database.GCCDatabase \
	    -a srcdir=`cd ../../gcc/testsuite && ${PWDCMD-pwd}` && \
	    echo timestamp > stamp-qmtest
Traceback (most recent call last):
  File "/opt/qmtest/bin/qmtest", line 126, in <module>
    qm.diagnostic.load_messages("test")
  File "/Users/ericgallager/Library/Python/2.7/lib/python/site-packages/qm/diagnostic.py", line 203, in load_messages
    diagnostic_file = qm.get_share_directory('messages', 'diagnostics.txt')
  File "/Users/ericgallager/Library/Python/2.7/lib/python/site-packages/qm/common.py", line 208, in get_share_directory
    return os.path.join(qm.prefix, qm.data_dir, *components)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/posixpath.py", line 70, in join
    elif path == '' or path.endswith('/'):
AttributeError: 'NoneType' object has no attribute 'endswith'
make: *** [stamp-qmtest] Error 1
```

**Comment by cooljeanius** [comment]
The only bug I can find in the GCC bugzilla referencing qmtest is 33612: https://gcc.gnu.org/bugzilla/show_bug.cgi?id=33612 

There haven't been any commits to GCC mentioning qmtest since 2012: https://gcc.gnu.org/git/?p=gcc.git&a=search&h=HEAD&st=commit&s=qmtest

**Comment by cooljeanius** [comment]
cc @stefanseefeld @qmtest

**Comment by jsm28** [comment]
If anyone seriously wishes to resurrect QMTest, I should do a better history conversion from the original SVN and CVS repositories to replace this git-svn one that's missing almost all the history. There were a sequence of rearrangement commits in SVN

```
------------------------------------------------------------------------
r1001 | root | 2006-12-05 04:17:21 +0000 (Tue, 05 Dec 2006) | 3 lines
Changed paths:
   A /qmtest/trunk (from /trunk:1000)
   D /trunk

Moving to qmtest subdirectory.


------------------------------------------------------------------------
r1000 | root | 2006-12-05 04:17:05 +0000 (Tue, 05 Dec 2006) | 2 lines
Changed paths:
   A /qmtest/tags (from /tags:999)
   D /tags

Moving to qmtest subdirectory.

------------------------------------------------------------------------
r999 | root | 2006-12-05 04:16:41 +0000 (Tue, 05 Dec 2006) | 2 lines
Changed paths:
   D /branches
   A /qmtest/branches (from /branches:998)

Moving to qmtest subdirectory.

------------------------------------------------------------------------
r998 | root | 2006-12-05 04:14:02 +0000 (Tue, 05 Dec 2006) | 2 lines
Changed paths:
   A /qmtest

Create qmtest directory.

------------------------------------------------------------------------
```
and everything before those didn't get converted by git-svn.

**Comment by stefanseefeld** [comment]
oh wow, a blast from the past !

I'm not entirely understand what the goal is here. Is GCC still using `qmtest` ? Or can those Makefile references be removed ? QMTest is indeed very old. Moving from Python2 to Python3 is the least problem. Quite a bit harder would be its use of Zope.
I forked QMTest into my own space (https://github.com/stefanseefeld/qmtest), and may have added some cleanup there (though I don't quite remember). At some point I started my own build tool (https://github.com/stefanseefeld/faber) where I hoped I could add some of QMTest's design ideas, but even that hasn't got much attention recently...

I don't think going back to svn history is really worthwhile at this point. It's likely easier to just re-implement whatever is missing.

But by all means, let me know if there is anything I can help with.

**Comment by cooljeanius** [comment]
> oh wow, a blast from the past !
> 
> I'm not entirely understand what the goal is here. Is GCC still using `qmtest` ? Or can those Makefile references be removed ? 

I mean, yes, I guess that could be another possible solution

> QMTest is indeed very old. Moving from Python2 to Python3 is the least problem. Quite a bit harder would be its use of Zope.

Zope still exists and works with modern versions of Python though? At least, the Zope packages in MacPorts have still been receiving updates as recently as this October...

> I forked QMTest into my own space ([stefanseefeld/qmtest](https://github.com/stefanseefeld/qmtest)), and may have added some cleanup there (though I don't quite remember). 

Ah, let me try that version; maybe if anyone still has commit access here, a link could be added to it?

**Comment by jsm28** [comment]
The makefile targets should have been removed from GCC long ago (as in, when README.QMTEST was removed in 2011, for example). Note that the entire qmtest_gcc extension (the equivalent of .exp files in the GCC repository, roughly) was not converted from SVN to git, in addition to almost all the commit history of QMTest itself.

I think the QMTest design has some advantages over that of DejaGNU, but major work would be needed to make it useful again (for anything, not necessarily GCC). Note also that the last actual change to qmtest_gcc was in 2005 (much of the work on it was to produce lsb-test-libstdcpp, I think); a huge amount has changed in both DejaGNU itself and the GCC testsuite since then.

**Comment by cooljeanius** [comment]
> The makefile targets should have been removed from GCC long ago (as in, when README.QMTEST was removed in 2011, for example).

OK, patch submitted to remove them: https://gcc.gnu.org/pipermail/gcc-patches/2023-December/639422.html

**Comment by cooljeanius** [comment]
> > The makefile targets should have been removed from GCC long ago (as in, when README.QMTEST was removed in 2011, for example).
> 
> OK, patch submitted to remove them: [gcc.gnu.org/pipermail/gcc-patches/2023-December/639422.html](https://gcc.gnu.org/pipermail/gcc-patches/2023-December/639422.html)

Update: committed: https://gcc.gnu.org/pipermail/gcc-patches/2023-December/639626.html

**Comment by jsm28** [comment]
I've now pushed a clean conversion of history from CVS and SVN; the former bad git-svn conversion remains available in the git-svn/* branches and tags. The branch tips of the new `main` branch and the old `git-svn/master` have the same contents, for example, but `main` has a full history of 853 commits where `git-svn/master` only had 43 commits. (History of the old qmtc extension from before it was merged into QMTest proper is in qmtc/* branches and tags. https://github.com/SourceryTools/qmtest_gcc has the history of qmtest_gcc.)

I don't have any plans to work further on QMTest myself, but if anyone does wish to resurrect it for some reason, you now have a complete history on the `main` branch as a basis for doing so rather than only the very incomplete old git-svn history.

**Comment by cooljeanius** [comment]
> I've now pushed a clean conversion of history from CVS and SVN; the former bad git-svn conversion remains available in the git-svn/* branches and tags. The branch tips of the new `main` branch and the old `git-svn/master` have the same contents, for example, but `main` has a full history of 853 commits where `git-svn/master` only had 43 commits. (History of the old qmtc extension from before it was merged into QMTest proper is in qmtc/* branches and tags. [SourceryTools/qmtest_gcc](https://github.com/SourceryTools/qmtest_gcc) has the history of qmtest_gcc.)
> 
> I don't have any plans to work further on QMTest myself, but if anyone does wish to resurrect it for some reason, you now have a complete history on the `main` branch as a basis for doing so rather than only the very incomplete old git-svn history.

OK thanks, I think I'll close this now. If there's any renewed interest in this, an issue can be opened in the new repo instead.
